# Generated by Django 5.2.1 on 2025-05-18 21:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
